name: jawad_rider_captain
description: "A new Flutter project."
publish_to: "none"

version: 1.0.5+1
environment:
  sdk: ">=3.10.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter

  flutter_localizations: 
    sdk: flutter
  intl: ^0.20.2
  dartz: ^0.10.1
  dio: ^5.5.0+1
  pretty_dio_logger: ^1.4.0
  hive_ce: ^2.15.1
  hive_ce_flutter: ^2.3.3
  get_it: ^8.0.3
  go_router: ^14.6.2
  gap: ^3.0.1
  icons_plus: ^5.0.0
  pinput: ^5.0.1
  smooth_page_indicator: ^1.2.1
  awesome_notifications: ^0.10.1
  auto_size_text:
  freezed_annotation:
  flutter_dotenv:
  flutter_advanced_switch: ^3.1.0
  cached_network_image_plus: ^0.0.5
  flutter_svg: ^2.0.17
  jiffy: ^6.3.2
  wolt_modal_sheet: ^0.6.1
  flutter_smart_dialog: ^4.9.8+5
  flutter_screenutil: ^5.9.3
  device_info_plus: ^11.2.0
  flutter_bloc: ^8.1.6
  bloc: ^8.1.4
  firebase_core: ^3.13.0
  firebase_messaging: ^15.2.5
  equatable: ^2.0.7
  lottie: ^3.3.0
  encrypt: ^5.0.3
  ai_barcode_scanner: ^6.0.1
  image_picker: ^1.1.2
  syncfusion_flutter_charts: ^28.1.36
  connectivity_plus: ^6.1.1
  screenshot: ^3.0.0
  rxdart: ^0.28.0
  video_player: ^2.9.2
  flutter_secure_storage: ^9.2.2
  salomon_bottom_bar: ^3.3.2
  flutter_rating_bar: ^4.0.1
  retrofit: ^4.4.0
  logger: ^2.5.0
  json_annotation: ^4.9.0
  google_maps_flutter: ^2.12.1
  onesignal_flutter: ^5.3.0
  flutter_foreground_task: ^9.1.0
  flutter_local_notifications: ^19.1.0
  location: ^8.0.0
  web_socket_channel: ^3.0.3
  permission_handler: ^12.0.0+1
  url_launcher: ^6.3.1
  audioplayers: ^6.4.0
  shimmer: ^3.0.0
  sliding_action_button: ^0.0.7
  webview_flutter: ^4.13.0
  sensors_plus: ^7.0.0
  flutter_compass: '^0.8.1'
  geolocator: ^14.0.2
  flutter_background_service: ^5.1.0
  simple_kalman: ^1.0.2
  geocoding: ^4.0.0
  file_picker: ^10.3.8
  share_plus: ^12.0.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.1
  change_app_package_name: ^1.4.0
  freezed: ^3.2.3
  json_serializable: ^6.10.0
  retrofit_generator: ^10.2.1
  hive_ce_generator: ^1.10.0
  build_runner: ^2.6.0


dependency_overrides:
  build_runner: ^2.4.5

flutter_assets:
  assets_path: assets/
  output_path: lib/core/constant/
  filename: app_image.dart
  field_prefix:


flutter:
  uses-material-design: true
  generate: true

  fonts:
    - family: Almarai
      fonts:
        - asset: assets/fonts/Almarai/Almarai-Regular.ttf
        - asset: assets/fonts/Almarai/Almarai-Bold.ttf

    - family: Poppins
      fonts:
        - asset: assets/fonts/Poppins/Poppins-Regular.ttf
        - asset: assets/fonts/Poppins/Poppins-Bold.ttf

  assets:
    - assets/
    - assets/svg/
    - assets/fonts/
    - assets/images/
    - .env
    - assets/lottie/
    - assets/map/
    - assets/fonts/Almarai/
    - assets/fonts/Poppins/
    - assets/video/
    - assets/sound.wav
